### ISSUE TITLE
Karma-webpack takes ~2 minutes to load

### ISSUE THREAD

**Issue by TheMcMurder** [webpack-contrib/karma-webpack#108]
Using 1.7.0 and webpack 1.12

When I start my unit tests I get an the following logs with `loglevel: config.LOG_DEBUG`

```
02 03 2016 09:19:46.010:DEBUG [plugin]: Loading karma-* from /.../node_modules
02 03 2016 09:19:46.013:DEBUG [plugin]: Loading plugin /.../node_modules/karma-chai.
02 03 2016 09:19:46.014:DEBUG [plugin]: Loading plugin /.../node_modules/karma-chai-as-promised.
02 03 2016 09:19:46.015:DEBUG [plugin]: Loading plugin /.../node_modules/karma-chai-sinon.
02 03 2016 09:19:46.017:DEBUG [plugin]: Loading plugin /.../node_modules/karma-chrome-launcher.
02 03 2016 09:19:46.021:DEBUG [plugin]: Loading plugin /.../node_modules/karma-coverage.
02 03 2016 09:19:46.207:DEBUG [plugin]: Loading plugin /.../node_modules/karma-firefox-launcher.
02 03 2016 09:19:46.209:DEBUG [plugin]: Loading plugin /.../node_modules/karma-mocha.
02 03 2016 09:19:46.210:DEBUG [plugin]: Loading plugin /.../node_modules/karma-nyan-reporter.
02 03 2016 09:19:46.257:DEBUG [plugin]: Loading plugin /.../node_modules/karma-sinon.
02 03 2016 09:19:46.258:DEBUG [plugin]: Loading plugin /.../node_modules/karma-webpack.
02 03 2016 09:21:50.288:DEBUG [karma]: List of files has changed, trying to execute
02 03 2016 09:21:50.289:WARN [karma]: No captured browser, open http://localhost:9876/
02 03 2016 09:21:50.291:DEBUG [watcher]: Watching "/.../app/index.test.js"
02 03 2016 09:21:50.294:INFO [karma]: Karma v0.13.19 server started at http://localhost:9876/
02 03 2016 09:21:50.298:INFO [launcher]: Starting browser Firefox
```

Notice that loading the karma-webpack takes a little under two minutes to load before the next line runs?

I inherited a fairly large app it has over 640 unit tests. But by far the thing that takes the longest is waiting for karma-webpack module to load. I am trying to figure out why it takes so long to load. 

Currently each test is required by the file that it is testing, like so: 

``` javascript
// inside custom-date-form directive
if (process.env.NODE_ENV === 'test') {
  require('./custom-date-form.test')(ngModule)
}
```

I have tried to fix it with a few configuration tweaks but I haven't seen any results. Is there a way I can figure out exactly why it is taking so long to load?

**Comment by tf** [comment]
I am seeing a similar problem. From what I have found out so far, it looks like `karma-webpack` triggers an initial Webpack run right when it is initialized. I was able to optimize test runtime (also on subsequent karma runs) by removing unneeded `entry` items from the Webpack config used by `karma.webpack` and moving to the "Alternative usage" proposed in the Readme. Before `karma-webkit` was basically recompiling the whole bundle for each test file.

**Comment by samithaf** [comment]
Experiencing the same issue with karma 0.13.22 and karma-webpack 1.7.0

**Comment by csvan** [comment]
What happens if you disable source maps? They are usually by far the largest culprits when it comes to webpack load times.

**Comment by hankthewhale** [comment]
@TheMcMurder @tf any resolution on this?

**Comment by TheMcMurder** [comment]
@hankthewhale no and unfortunately I no longer have access to the project where this is an issue.
