### ISSUE TITLE
Future Path of karma-webpack

### ISSUE THREAD

**Issue by MikaAK** [webpack-contrib/karma-webpack#179]
## Decisions

A couple weeks ago we decided that there were two options for future development with karma-webpack
1) Continue to maintain the old codebase and refactor as we go
2) Restart from scratch with a better set of code rules and more thorough testing

It was decided option 2 would be the easiest path so we're going to gut the repo and start over. Version 1.x will still be on npm and in the v1 branch of this repo. 
### What this means

This means development and fixes will most likely halt unless extremely urgent while we rewrite karma-webpack. Hopefully while rewriting we can take into account a few issues such as #165, #130, #149 and performance.

CC: @d3viant0ne @DanielaValero @goldhand @jon301 @carlos-

**Comment by UnsungHero97** [comment]
is there a new branch for the rewrite?

**Comment by d3viant0ne** [comment]
@UnsungHero97 - I'm pretty sure the 2.0 work will be done on master. [v1 Branch](https://github.com/webpack/karma-webpack/tree/v1) will be used for maintenance of the existing Karma Webpack release version.

**Comment by dignifiedquire** [comment]
@d3viant0ne `master` is currently void of any code, which is a bit odd. `src/index.js` is empty and `index.js` points to `lib` folder which is not checked into git.

**Comment by d3viant0ne** [comment]
@dignifiedquire - #master is being completely rewritten. Legacy code & any current release / tags are on the v1 branch.

It's not something that could be merged down into master. Tagging a `v1` branch was decided to be the path of least resistance.

**Comment by dignifiedquire** [comment]
Okay, thanks, might be good to have a warning though, as it is the default that people come in to and there is just nothing there anymore, it looks like it was an accident.

**Comment by d3viant0ne** [comment]
@dignifiedquire - Most of the planning has been done in Slack. I'll put a note in the Readme on #master

**Comment by DanielaValero** [comment]
Hello @d3viant0ne @dignifiedquire I just opened a PR to add some documentation about the setup for contributors for the rewrite and added in the same PR also a note about the rewrite. PR is #185

**Comment by dignifiedquire** [comment]
Thank you @DanielaValero
