### ISSUE TITLE
It seems `karma-webpack` does not respect webpack's configuration of `resolve.modules`

### ISSUE THREAD

**Issue by JounQin** [webpack-contrib/karma-webpack#209]
**I'm submitting a bug report**

I'm using `stylus` with `webpack`, it works well without karma.

``` stylus
// src/components/Demo/index.styl
// folder of `demo.jpg` is `src/assets/demo.jpg`
// we have `resolve.modules` config: `[paths.src(), paths.base('packages'), 'node_modules']`
// without karma, it works very well
.demo
  background-image url('assets/demo.jpg')
```

But when running with karma, it throws error:

``` bash
ERROR in ./~/css-loader?{"minimize":false,"sourceMap":true}!./~/stylus-loader?sourceMap!./src/components/Demo/index.styl
Module not found: Error: Can't resolve './assets/demo.jpg'
```

When I change my stylus code to:
``` stylus
.demo
  background-image url('../../assets/demo.jpg')
```
Karma will resolve image path correctly

**Webpack version:**
2.2.0

**Webpack Karma version**:
2.0.1

**Karma version**:
1.4.0

**Please tell us about your environment:**
macOS sierra

**Browser:**
PhantomJs

**Current behavior:**
Throw error

**Expected/desired behavior:**
resolve image path correctly

part of my `karma.config.js`:
``` js
const config = {
  webpack: {
    devtool: webpackConfig.devtool,
    resolve: webpackConfig.resolve,
    resolveLoader: webpackConfig.resolveLoader,
    plugins: webpackConfig.plugins,
    module: {
      rules: webpackConfig.module.rules
    },
    node: webpackConfig.node,
    performance: false
  }
}
```

**Comment by marcbachmann** [comment]
It also doesn't respect `resolveLoader`

**Comment by roopkt** [comment]
Sorry for writing in closed issue however I wanted to know the resolution or workaround to this issue.
Hey I am facing the same issue I have all my code using resolve key to import the file modules.
And in my karma tests it is failing syaing module not found error cannot resolve '@libpath...
Does anyone one know what is the workaround here.

**Comment by wangcheng007** [comment]
Did you solved it? i am facing the same problem also

**Comment by wangcheng007** [comment]
have you sloved it?i am also facing the same problems
