### ISSUE TITLE
"ReferenceError: exports is not defined" with webpack 2.2.1

### ISSUE THREAD

**Issue by TaylorBriggs** [webpack-contrib/karma-webpack#229]
**I'm submitting a bug report**

**Webpack version:**
2.2.1

**Webpack Karma version**:
2.0.2

**Karma version**:
1.5.0

**Please tell us about your environment:**
OSX 10.11.6

**Browser:**
Firefox 51.0.1 (64-bit)

**Current behavior:**
```
Firefox 51.0.0 (Mac OS X 10.11.0) ERROR
  ReferenceError: exports is not defined
  at test/test_index.coffee:22489
Firefox 51.0.0 (Mac OS X 10.11.0): Executed 0 of 0 ERROR (0.761 secs / 0 secs)
```

**Expected/desired behavior:**
```
Firefox 51.0.0 (Mac OS X 10.11.0): Executed 2688 of 2688 SUCCESS
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**

Steps to reproduce:
```
$ NODE_ENV=test karma start
```

package.json:
https://gist.github.com/TaylorBriggs/1a37e3078e6c552f78d49d57838661a9

Karma config: 
https://gist.github.com/TaylorBriggs/e4b395c07f9da76dd6adc343dff5020e

* **What is the expected behavior?**
The tests should run as usual before updating to webpack 2.2.1 and karma-webpack 2.0.2

**Comment by rohmanhm** [comment]
Got same problem

**Comment by TaylorBriggs** [comment]
Tracked it down to a wepack 2 issue: https://github.com/webpack/webpack/issues/2631

Looks like I need to stop using `add-module-exports` and refactor to `require('x').default`.
