### ISSUE TITLE
“request.replace is not a function” error

### ISSUE THREAD

**Issue by Vaccano** [webpack-contrib/karma-webpack#241]
**I'm submitting a bug report**

**Webpack version:**
2.3.2

**Webpack Karma version**:
2.0.3

**Karma version**:
1.5.0

**Please tell us about your environment:**
Windows 7

**Browser:** Chrome 57

**Current behavior:**
When running `karma start` I get the following error:

> TypeError: request.replace is not a function

Note: This error does not happen when I run my normal webpack based project.

**Expected/desired behavior:**

No error would be generated.  Here are my config files:

[karma.conf.js](https://gist.github.com/Vaccano/390b5e9c19c4f314baf32c2d07e032c2#file-karma-conf-js) - [webpack.config.js](https://gist.github.com/Vaccano/390b5e9c19c4f314baf32c2d07e032c2#file-webpack-config-js) - [package.json](https://gist.github.com/Vaccano/390b5e9c19c4f314baf32c2d07e032c2#file-package-json)- [yarn.lock](https://gist.github.com/Vaccano/390b5e9c19c4f314baf32c2d07e032c2#file-yarn-lock)

* **What is the expected behavior?**

From what I can see, this error is generated by webpack when more than one entry point is used.  It seems that karma-webpack creates more than one entry point for the tests.   So the "expected behavior is to either only have one entry point, or find a way around this error.

**Comment by ordinaryorange** [comment]
@Vaccano  I hit this exact same error today. For me it was the inclusion of `AureliaPlugin()` when I had no `entry:` specified. See [this bug](https://github.com/aurelia/webpack-plugin/issues/134) report. Although I notice that you have an `entry:` defined. Maybe try commenting out the other plugins and the ctor you have defined for `AureliaPlugin()` see what happends then ?
