### ISSUE TITLE
Support webpack 3 in peerDependencies

### ISSUE THREAD

**Issue by chearon** [webpack-contrib/karma-webpack#244]
I was able to use karma-webpack with webpack 3 and had no issues. I haven't looked much at the source but it appears to be compatible, the number of breaking changes from 2 to 3 was small.

Thanks!

<hr>

**I'm submitting a feature request**

**Webpack version:**
3.0.0

**Webpack Karma version**:
2.0.3

**Please tell us about your environment:**
macOS

**Browser:** Chrome latest

**Current behavior:**
> warning "karma-webpack@2.0.3" has incorrect peer dependency "webpack@^1.1.0 || ^2 || ^2.1.0-beta.0 || ^2.2.0-rc.0"

**Expected/desired behavior:**
Silent install

**Comment by floriancargoet** [comment]
Even if it works, we cannot use `npm shrinkwrap --dev` until this is updated.
```
npm shrinkwrap --dev                 
npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! peer invalid: webpack@^1.1.0 || ^2 || ^2.1.0-beta.0 || ^2.2.0-rc.0, required by karma-webpack@2.0.3
npm ERR! peer invalid: webpack@1 || ^2.1.0-beta || ^2.2.0-rc.0, required by webpack-dev-middleware@1.10.1

```

**Comment by d3viant0ne** [comment]
`karma-webpack@2.0.4` is out on npm

**Comment by floriancargoet** [comment]
@d3viant0ne Thank you very much!

**Comment by pedroabreu** [comment]
`webpack-dev-middleware "^1.0.11"` is still a dependency for karma-webpack v2.0.4 . Is there any plan on updating it to `v1.11.0` to avoid this warning ?

Thanks for your work guys 👍
