### ISSUE TITLE
[Bug] Cannot declare global variables

### ISSUE THREAD

**Issue by luchillo17** [webpack-contrib/karma-webpack#246]
**I'm submitting a bug report**

**Webpack version:**
2.6.1

**Webpack Karma version**:
2.0.3

**Karma version**:
1.7.0

**Please tell us about your environment:**
OSX 10.12.5
**Browser:** Electron through `karma-electron` package, not `karma-electron-launcher`.

**Current behavior:**
I cannot define global variables, i've tried with a shim.js file on top in karma `files` property, which says `ReferenceError: global is not defined`, adding it to the `DefinePlugin` object in the `webpack.test.config.ts` get rid of the error log but the var i add in other file get's overwritten, or never existed in current file.

**Expected/desired behavior:**
Being able to define global variable for the whole test suite, for all files in the `files` property of karma config.

**Comment by schmkr** [comment]
Hey @luchillo17, I had this problem too, but solved this by creating a js file that is not processed by this preprocessor but declares the variables I need globally. That file is added to the `files`-array in `karma.config.js` before the files that will be processed by `karma-webpack`.

**Comment by luchillo17** [comment]
I don't remember what i did about this but i don't have such issue any more.

**Comment by kresli** [comment]
anyone could provide an example how to solve it please? thanks
