### ISSUE TITLE
karma-webpack not properly loading babelrc

### ISSUE THREAD

**Issue by kyleholzinger** [webpack-contrib/karma-webpack#266]
## **BEFORE YOU SUBMIT** please read the following:

**I'm submitting a bug report**

**Webpack version:**
3.0

**Webpack Karma version**:
2.0.5

**Karma version**:
1.3.0

**Please tell us about your environment:**
OSX 10.12
**Browser:** [Phantom 2.1.1]

**Current behavior:**
karma-webpack does not properly load babelrc presets

**Expected/desired behavior:**
karma-webpack should read from babelrc and load the specified presets

Steps to reproduce: enable babel-env and the stage 3 preset, and use an object destructuring inside of one of the files passed to karma-webpack

* **What is the motivation / use case for changing the behavior?**
I want to be able to use my babelrc

**Comment by kyleholzinger** [comment]
Was this fixed @michael-ciniawsky ?

**Comment by kuguarpwnz** [comment]
Renaming to `babel.config.json` may help.
