### ISSUE TITLE
Still using old version of webpack-dev-middleware that doesn't support webpack 3.x

### ISSUE THREAD

**Issue by JayAndCatchFire** [webpack-contrib/karma-webpack#268]
**I'm submitting a bug report**

**Webpack version:**
3.7.1

**Webpack Karma version**:
2.0.5

**Karma version**:
1.7.1

**Please tell us about your environment:**
OSX 10.12.6 (16G29)

**Current behavior:**
Installing karma-webpack warns with:
```
warning "webpack-dev-middleware@1.10.1" has incorrect peer dependency "webpack@1 || ^2.1.0-beta || ^2.2.0-rc.0".
```

**Expected/desired behavior:**
webpack-dev-middleware is already at version 1.12.0.  We should probably upgrade to that.  It includes webpack 3.x as a peer dependency.

**Comment by michael-ciniawsky** [comment]
`"webpack-dev-middleware": "^1.0.11"` the dependency uses the `^` semver range (minor/patch), so `npm update` should pull  a newer version if available, maybe you need to clean your `npm cache` beforehand. Feel free to send a PR updating the minimum to `^1.2.0`

**Comment by JayAndCatchFire** [comment]
You're right.  I should be picking up 1.2.0 in that case.  I'm using Yarn.  Maybe it's doing something weird.  In any case, I'll send a PR your way.

**Comment by d3viant0ne** [comment]
@JayAndCatchFire - Older version stuck in a lock file? Also, what version of Yarn

**Comment by JayAndCatchFire** [comment]
@d3viant0ne It very well could be a lock file issue.  The yarn version is either 1.2.0 or 1.2.1.  (It was my work machine and I don't have it handy at the moment.)

**Comment by AlexEvanczuk** [comment]
@JayAndCatchFire 
I had the same problem, and I did have an older version stuck in the lock file.  I removed my lock file and reinstalled and it installed the newest version of `webpack-dev-middleware`.
