### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by adrice727** [webpack-contrib/karma-webpack#276]
**I'm submitting a bug report**

**Webpack version:**
webpack@3.8.1

**Webpack Karma version**:
karma-webpack@2.0.5

**Karma version**:
karma@1.7.1

**Please tell us about your environment:**
OSX 10.12.6

**Browser:** [Chrome 62.0.3202]

**Current behavior:**
When running tests, I'm getting the following error:
```
Uncaught ReferenceError: require is not defined
```
![console error](http://i65.tinypic.com/am83mh.png)

**Expected/desired behavior:**

`require` should be defined.

My `karma.conf.js` and `webpack.config.js` are available [here](https://gist.github.com/adrice727/12d536d06b92d2f22ad936969069f3f5).

**Comment by MattGoldwater** [comment]
Did you fix this? If so, how?

**Comment by inickel** [comment]
any idea for this issue? @adrice727

**Comment by davidmpaz** [comment]
@adrice727 could you provide some feedback on your outcome with this issue?

**Comment by finorix079** [comment]
How was this one fixed? I am facing exactly the same issue and can't find any resolution.

**Comment by codymikol** [comment]
@terryjiang2020 

You're running code dependant on commonjs in an environment where that is not recognized. It's not an issue with karma-webpack.

Look up CommonJS and ES Modules. Get a good understanding of what they are, how their APIs work, and what runtimes they can be used in. If you do that, you will have the answer to your question.
