### ISSUE TITLE
Regression in v2.0.8 using webpack file-loader 

### ISSUE THREAD

**Issue by gdetrez** [webpack-contrib/karma-webpack#284]
**I'm submitting a bug report**

**Webpack version:** 3.10.0

**Webpack Karma version**: 2.0.8

**Karma version**: 1.7.1

**Please tell us about your environment:** Linux

**Browser:** Chrome

**Current behavior:**
I have tests that looks a bit like this:
```js
import image from './test.png';
...
fetch(image).then(response => /* some test that use the image */)'
```

This used to work fine but with the release of 2.0.8, it doesn't work anymore.
In the output, I can see that:
```
14 12 2017 15:53:46.483:WARN [web-server]: 404: /tmp/gregoire/_karma_webpack_8a5c1d368c47a24658318f24915284d7.png
```
I think that the introduction of the tmpdir is preventing karma from finding the image emitted by webpack...

**Expected/desired behavior:**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**
I made a repository that shows the problem: https://github.com/gdetrez/karma-webpack-issue

* **What is the expected behavior?**
The `image` variable should contain the path where karma serves the image.

* **What is the motivation / use case for changing the behavior?**
Regression?

**Comment by darsee** [comment]
Should there be a trailing slash [here](https://github.com/webpack-contrib/karma-webpack/pull/279/files#diff-1bc56a1b4b855af7b16012fcf5210059R136)?

**Comment by michael-ciniawsky** [comment]
@darsee I think so, could you spin up a quick PR ? :)
@gdetrez Could you please try out the fix suggested by @darsee locally ?

**Comment by darsee** [comment]
Also, I think prior to `2.0.8`, [`webpackOptions.output.path`](https://github.com/webpack-contrib/karma-webpack/blob/master/src/karma-webpack.js#L51) would have a trailing slash if `indexPath` was empty but now it won't. Likewise [`webpackOptions.output.publicPath`](https://github.com/webpack-contrib/karma-webpack/blob/master/src/karma-webpack.js#L52) if `publicPath` was empty.

Sure, I'll attempt a PR :)

**Comment by michael-ciniawsky** [comment]
Thx very much in advance 🤗 , hopefully #279 didn't break more then that 🤕

**Comment by gdetrez** [comment]
Sorry for the delay. I just tried 2.0.9 and the problem is still there. I can't re-open the issue though, should I create a new one?

**Comment by gdetrez** [comment]
The trailing slash is an improvement but I still get a 404:
```
22 12 2017 14:57:05.039:WARN [web-server]: 404: /tmp/gregoire/_karma_webpack_/8a5c1d368c47a24658318f24915284d7.png 
```

**Comment by PSpSynedra** [comment]
We still get 404 errors using:
- webpack-3.10.0
- file-loader-1.1.6
- karma-1.7.1
- karma-webpack-2.0.9

Anything loaded with file-loader results in a 404 in the log:
```javascript
import TestImageURL from '!!file-loader!images/test_image.jpg';
````
`05 02 2018 14:47:09.323:WARN [web-server]: 404: /tmp/_karma_webpack_/d400964494249568d17dd633f90b836d.jpg`

@gdetrez: did you open a new issue or sovle it somehow?

**Comment by gdetrez** [comment]
@PSpSynedra No, I haven't opened a new issue. There's  #291 that seems a bit similar but I haven't looked in details so maybe not. My current solution is to pin the version of karma-webpack to 2.0.7.

**Comment by gdetrez** [comment]
@michael-ciniawsky @PSpSynedra At least for our use case, it seems that 2.0.13 finally solved this issue :tada:

**Comment by PSpSynedra** [comment]
@gdetrez Same here. With 2.0.13 it is gone and everything works fine.
