### ISSUE TITLE
2.0.10 and 2.0.11 not compatible with node < 8

### ISSUE THREAD

**Issue by IgorAufricht** [webpack-contrib/karma-webpack#308]
## **BEFORE YOU SUBMIT** please read the following:

**I'm submitting a bug report**

**Webpack version:**
3.x

**Webpack Karma version**:
2.0.11

**Karma version**:
1.7.1

**Current behavior:**
Updating `source-map` dependency to 0.7.0 in `karma-webpack@2.0.10` ([here](https://github.com/webpack-contrib/karma-webpack/commit/0a5564d8278a8846d40b8b8c3731023b5a3f8080#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R33)) breaks compatibility with node versions < 8, since the [source-map 0.7.0 dropped support for node < 8](https://github.com/mozilla/source-map/blob/master/CHANGELOG.md#070).

**Expected/desired behavior:**
The `package.json` of `karma-webpack` says it should be compatible with node >= 4, so it should still work correctly with node < 8.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**
Install the latest `karma-webpack` with node < 8.

Thanks.

**Comment by michael-ciniawsky** [comment]
Released in [`v2.0.12`](https://github.com/webpack-contrib/karma-webpack/releases/tag/v2.0.12) 🎉

**Comment by IgorAufricht** [comment]
@michael-ciniawsky Thank you for the quick fix. :)

**Comment by tarjei** [comment]
Hi, I would love to be able to set the source-map version myself as source-map 0.7.0 has some very interesting optimizations that I want to utilize. Is it possible to allow for both versions?
