### ISSUE TITLE
Upgrade webpack-dev-middleware dependency

### ISSUE THREAD

**Issue by mikegreiling** [webpack-contrib/karma-webpack#314]
**I'm submitting a bug report**

**Webpack version:**
4.0.1

**Webpack Karma version**:
2.0.7

**Karma version**:
2.0.0

**Please tell us about your environment:**
OSX 10.13.3

**Browser:** Chrome 64, Safari 11.0.3

**Current behavior:**
Currently karma-webpack has `webpack-dev-middleware` 1.12.0 listed as a dependency.  This is two major versions behind the current release (3.0.0).

Despite #301 having added webpack v4.x as a `peerDependency`, installing this alongside webpack 4.0.1 will still display warnings because `webpack-dev-middleware` does _not_ list webpack 4.x as a valid peer.  `yarn check` will actually throw an error because of this.

This is the primary roadblock for my project to upgrade to webpack v4.  Our CI will not accept anything for which `yarn check` produces an error.

**Expected/desired behavior:**

karma-webpack should use `webpack-dev-middleware` v2.0.6 which has compatibility with webpack v2.2-4.0, or release a new major version that uses `webpack-dev-middleware` v3.0.0 and drops compatibility with webpack 2 and 3.

* **What is the motivation / use case for changing the behavior?**

wanting to use webpack 4 without warnings in my console when installing packages

**Comment by limonte** [comment]
For [sweetalert2](https://github.com/sweetalert2/sweetalert2) the outdated dependency on `webpack-dev-middleware` possibly causes the "Some of your tests did a full page reload!" issue: https://github.com/sweetalert2/sweetalert2/issues/986

**Comment by philipahlberg** [comment]
#316 might be related
