### ISSUE TITLE
Bug: webpack 4 using Angular 1.6

### ISSUE THREAD

**Issue by rbatllet** [webpack-contrib/karma-webpack#327]
**Webpack version:**
4.8.3

**Webpack Karma version**:
3.0.0

**Karma version**:
2.0.2

**Please tell us about your environment:**
OSX 10.13.4

**Browser:** Chrome 66.0, Firefox 60.0

**Current behavior:**
Unable to find the Angular provider with this Webpack Karma version and Webpack version. 
**See**: [link](https://errors.angularjs.org/1.6.10/$injector/unpr?p0=eProvider%20%3C-%20e)

![screen shot 2018-05-14 at 18 36 06](https://user-images.githubusercontent.com/3993987/40010663-b653d46c-57a5-11e8-8d50-19ecfef5d6f3.png)

**Expected/desired behavior:**
It Works fine with **Webpack 3.11.0** and **Karma Webpack 3.0.0**:

![screen shot 2018-05-14 at 18 38 45](https://user-images.githubusercontent.com/3993987/40010779-1ca12832-57a6-11e8-97a0-cefd63804b9e.png)

**Comment by AlonMiz** [comment]
Seems like you are minifing your bundle without ng-annotate.
try adding `
{
...
mode: 'development'
...
}`
to your webpack config file

**Comment by rbatllet** [comment]
@AlonMiz works GREAT.

Thank you very much!
