### ISSUE TITLE
Karma webpack color option

### ISSUE THREAD

**Issue by spicalous** [webpack-contrib/karma-webpack#332]
**I'm submitting a feature request**

It would improve consistency of configs if webpack's `color` config inherits Karma's `color` config

* **What is the motivation / use case for changing the behavior?**

Would provide more consistency, similar to the same way that webpack currently uses Karma's `singleRun` config to determine the `watch` config:
https://github.com/webpack-contrib/karma-webpack/blob/master/src/karma-webpack.js#L42

**Proposed behaviour**

As a suggestion, the value could be determined as follows: Taking the next item in the list if the previous one is not defined:

* webpack's color config value
* karma's color config value
* webpack's default color value (same as it is now)

**Next step**

I could contribute this and open a PR in the near future if the majority of the maintainers agree?

Thanks in advance!

Docs for reference

Webpack stats color docs: https://webpack.js.org/configuration/stats/?_sm_au_=iVVJFnC5DW5NQLFF#stats
Karma docs for color http://karma-runner.github.io/2.0/config/configuration-file.html

**Comment by michael-ciniawsky** [comment]
Feel free to send a PR :)
