### ISSUE TITLE
The `output.filename` should end with `.js`.

### ISSUE THREAD

**Issue by sechel** [webpack-contrib/karma-webpack#334]
There are certain issues with your current config 
https://github.com/webpack-contrib/karma-webpack/blob/1ac16eaa7b11ee154a2127d4f03cbfd1a81533f6/src/karma-webpack.js#L65 

For instance the folks over at [`html-webpack-plugin`](https://github.com/jantimon/html-webpack-plugin) filter all assets that do not end with `.js`, thus all `.html` files emitted stay empty when built alongside the test bundle using karma webpack.
Another thing is that `webpack-dev-middleware` doesn't recognize the mime type, e.g, when using a `typescript` `.ts` input file and this leads to other problems in browsers. One could solve this with a simple `mime: { 'text/javascript': ['ts'] }` but this seems hacky to me.

Anyway, I wanted to drop a line and see if we could get a discussion running on the matters.
Greetings
Stefan

**Comment by nanomosfet** [comment]
why cant you just name append `.js` to the end of your name `'[name] + '.js'`?

**Comment by sechel** [comment]
Yes but the plugin constructor of `karma-webpack` overwrites the settings I'm doing in my `webpack.config.js` or do I miss something here?

**Comment by jantimon** [comment]
Imho @sechel is right it should be karma-webpack/src/karma-webpack.js line 65 has to be changed to include the `.js` extension.

Is there any reason why it does not use an extension here?
