### ISSUE TITLE
Outputs can have multiple assets

### ISSUE THREAD

**Issue by 43081j** [webpack-contrib/karma-webpack#355]
Similar to #350. 

If an input has multiple output assets, an error will be thrown as the path will be an array rather than string. 

This is because `assetsByChunkName` entries can be arrays:

https://webpack.js.org/api/stats/

But in karma webpack, we assume it is always a string:

https://github.com/webpack-contrib/karma-webpack/blob/d42c5418d93508c94d40031c42ca7107dd6f1a73/src/karma-webpack.js#L174

Using the source maps loader will cause this error as one js file will produce a map and a js asset

**Comment by michael-ciniawsky** [comment]
I see, would you mind trying to send PR to fix this ? Checking for an `{Array}` and setting each item  (entry) individually should be sufficient

**Comment by michael-ciniawsky** [comment]
cc @rynclark :)

**Comment by rynclark** [comment]
Ill take a look later!

**Comment by michael-ciniawsky** [comment]
External sourcemaps currently don't seem work with `karma-webpack` according to the issue tracker, maybe we can fix that now aswell 🤔, but please let us focus on fixing the `Path must be a string...` issue first :) Should make it easier if we can ignore the `.map` file for now. Hopefully `assetsByChunkName` is deterministic 🙃

**Comment by GreenGremlin** [comment]
This also happens if a js file imports a css file. Possibly, only when using the extract-text-webpack-plugin.

**Comment by thijstriemstra** [comment]
fyi, also seeing this with 4.0.0 rc2:

```
08 09 2018 02:13:38.035:ERROR [karma]: TypeError: Path must be a string. Received [ 'spec/wavesurfer.spec.js', 'spec/wavesurfer.spec.js.map' ]
    at assertPath (path.js:28:11)
    at Object.join (path.js:1236:7)
    at Plugin.<anonymous> (/Users/foo/projects/wavesurfer.js/node_modules/karma-webpack/lib/karma-webpack.js:286:70)
    at Plugin.readFile (/Users/foo/projects/wavesurfer.js/node_modules/karma-webpack/lib/karma-webpack.js:305:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by Bobsans** [comment]
+1
karma-webpack: ^4.0.0-rc.2

I use **vue** and **mini-css-extract-plugin**

```
10 09 2018 11:47:59.087:ERROR [karma]: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at assertPath (path.js:39:11)
    at Object.join (path.js:434:7)
    at Plugin.<anonymous> (D:\WORK\Python\IlvoCRM\node_modules\karma-webpack\lib\karma-webpack.js:286:70)
    at Plugin.readFile (D:\WORK\Python\IlvoCRM\node_modules\karma-webpack\lib\karma-webpack.js:305:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```
and **this.outputs** is:
```
{
	"../test/components/Fa.spec.js":"..\\test\\components\\Fa.spec.f35f.js",
	"../test/components/Loader.spec.js":[
		"..\\test\\components\\Loader.spec.css",
		"..\\test\\components\\Loader.spec.f35f.js"
	],
	"../test/components/Url.spec.js":"..\\test\\components\\Url.spec.f35f.js"
}

```

**Comment by alabbas-ali** [comment]
Please check PR https://github.com/webpack-contrib/karma-webpack/pull/357

**Comment by 43081j** [comment]
Some regression or something happened with this...

With 3.0.5, test runs now do complete but some craziness goes on with multiple outputs.

If you have the sourcemaps loader enabled, for example, the resulting JS has _two different_ sourcemaps so they fail to load correctly in chrome. Installing 3.0.0 makes it work again, so we've definitely introduced a bug somewhere.

```js
foo;
// sourceMap;url=...
// sourceMap:url=...
```

This is the kind of thing we end up with.

**Comment by didi0613** [comment]
The same thing happened here with version `4.0.0-rc.2`
Error:
```
19 11 2018 14:16:25.525:ERROR [karma-server]: TypeError: Path must be a string. Received [ 'node_modules/electrode-archetype-react-component-dev/config/karma/entry.style.0ca30711e2d0162e57a8.css',
  'node_modules/electrode-archetype-react-component-dev/config/karma/entry.style.0ca30711e2d0162e57a8.css.map',
  'node_modules/electrode-archetype-react-component-dev/config/karma/entry.style.0ca30711e2d0162e57a8.css.map' ]
```

**Comment by rynclark** [comment]
Does `4.0.0-rc.3` fix this for you?

**Comment by thijstriemstra** [comment]
No, I'm still seeing this https://github.com/webpack-contrib/karma-webpack/issues/355#issuecomment-419597022 with rc3.

**Comment by thijstriemstra** [comment]
@matthieu-foucault resulting `stats.json`:

```json
{
  "assetsByChunkName": {
    "videojs.record": [
      "css/videojs.record.min.css",
      "videojs.record.min.js",
      "videojs.record.min.js.map"
    ]
  }
}
```

**Comment by matthieu-foucault** [comment]
@thijstriemstra: I finally found some time to look into this, using your project (`collab-project/videojs-record`) to debug the issue. 
What you are experiencing is a different issue, due to the fact that your webpack `output.filename` is a static name, which is a problem since you have more that a single entry point when testing with karma (each test file is an entry point), and they all end up being emmited to the same output.
I am still investigating as to why this now fails when it seems that it worked with `beta.0`, but that's a separate issue.
In the meantime, it seems that using `[name].js` as `output.filename` works around the issue.
