### ISSUE TITLE
Upgrade Webpack peer dependency

### ISSUE THREAD

**Issue by bbougot** [webpack-contrib/karma-webpack#358]
* Operating System: Windows 10
* Node Version: 10.10
* NPM Version: 6.4.0
* webpack Version: 4.19.0
* karma-webpack Version: 3.0.5

### Feature Proposal
Upgrade peer dependency to work with Webpack ^4.x.x
When I use karma-webpack with latest versions, I get the warning message in the console:
karma-webpack@3.0.5 requires a peer of webpack@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.

### Feature Use Case
Resolving Webpack dependency makes no warning again.

**Comment by michael-ciniawsky** [comment]
```bash
npm i -D karma-webpack@next
```
