### ISSUE TITLE
'The "path" argument must be of type string' since 4.0.0-rc.1

### ISSUE THREAD

**Issue by ara4n** [webpack-contrib/karma-webpack#363]
* Operating System: macOS 10.14
* Node Version: v10.9.0
* NPM Version: 6.4.1
* webpack Version: 4.20.2
* karma-webpack Version: 4.0.0-rc.2 and rc.1

### Actual Behavior

Karma crashes out shortly after launch with:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at assertPath (path.js:39:11)
    at Object.join (path.js:1157:7)
    at Plugin.<anonymous> (/Users/matthew/workspace/vector-web/node_modules/karma-webpack/lib/karma-webpack.js:286:70)
    at Plugin.readFile (/Users/matthew/workspace/vector-web/node_modules/karma-webpack/lib/karma-webpack.js:305:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```
4.0.0-beta.0 is okay; but rc.1 and rc.2 exhibit the problem.

Looks like a regression in https://github.com/webpack-contrib/karma-webpack/commit/ab4dde9a7b859e815e11925a0f5cc5c986360264 which happens when `stats.assetsByChunkName[entry]` returns an array of assets rather than a single asset.  Then when calculating the tmp filename to be read, path.join() crashes out because it's trying to concatenate an array rather than a string.

In this instance (https://github.com/vector-im/riot-web/tree/matthew/webpack4) it's because the `test/all-tests.js` entryPath has two assets: `bundles/d918c3aa7df7ca65ad57/test/all-tests.js` and `bundles/d918c3aa7df7ca65ad57/test/all-tests.css`.

**Comment by wilkie** [comment]
I've even gotten something like this where it gave that error in 3.0.5 (but tells me it "Received type undefined") but not when I downgraded to 3.0.0 (which is the version I'm using on a different project) where it all works just fine.

From my own very rudimentary debugging... there is some kind of "outputs" array that isn't generated properly (and not used at all in 3.0.0) and I'm not sure why.

**Comment by bluepnume** [comment]
Any traction on this one? I'm attempting to upgrade to webpack 4 and having problems getting karma working with karma-webpack rc.2

**Comment by Ivaylo-Lafchiev** [comment]
I am also having the same problem. Everything after karma-webpack@3.0.0 doesn't work because of the above error (or variations of it), with either karma@1.7.1 or karma@latest.

**Comment by matthieu-foucault** [comment]
Fixed in #361 and released. 
Use `npm i -D karma-webpack@next` to update.

**Comment by chrisnicola** [comment]
I still see this intermittently on rc.6.

**Comment by johnny-mh** [comment]
@matthieu-foucault I still see this issue on rc.6

**Comment by matthieu-foucault** [comment]
Sorry but my focus isn't on this project at the moment, and likely won't be in the future. You'll have to find someone else willing to maintain it.

**Comment by Ivaylo-Lafchiev** [comment]
> Sorry but my focus isn't on this project at the moment, and likely won't be in the future. You'll have to find someone else willing to maintain it.

What does this mean for the future of Karma? Should we be moving to something like Jest?

**Comment by matthieu-foucault** [comment]
Jest definitely has more support at the moment. I've been helping on this
plugin for a few months and been the only one making releases.
