### ISSUE TITLE
Dynamic import spy not working

### ISSUE THREAD

**Issue by MountainDrew** [webpack-contrib/karma-webpack#371]
* Operating System: macOS Sierra: 10.12.6
* Node Version: 8.11.3
* NPM Version: 5.6.0
* webpack Version: 3.12.0
* karma-webpack Version: 3.0.5

### Expected Behavior
When I spy upon `System.import` like:

`spyOn(System, 'import').and.returnValue(Promise.resolve('value to be returned'));`

and call like this:

`System.import('not real route');`

I expect to receive:

`Promise -> 'value to be returned'`

### Actual Behavior

when run:
<img width="955" alt="screen shot 2018-11-06 at 10 59 10" src="https://user-images.githubusercontent.com/20781479/48060212-42264500-e1b3-11e8-9c70-2905288fc6ce.png">

### Code

```js
    spyOn(System, 'import').and.returnValue(Promise.resolve('value to be returned'));

    console.log(System.import('not real route'));
```

### How Do We Reproduce?
Follow expected behavior.

**Comment by evilebottnawi** [comment]
@MountainDrew `System.import` deprecated in `webpack@4` and will be remove in `webpack@5`, better avoid using this

**Comment by MountainDrew** [comment]
@evilebottnawi - good to know, thanks! With the alternative being `import` (https://whatwg.github.io/loader/#loader-import), would you recommend `spyOn(Loader, 'import')`?

**Comment by MountainDrew** [comment]
@evilebottnawi -  ah my bad. It's just a method to overwrite the implemented function, effectively stubbing it. It checks a number of things like called with/number of times... I was effectively asking which Prototype it is built off?

**Comment by MountainDrew** [comment]
Happy to close this issue. I guess it's a no need to fix 👍

**Comment by evilebottnawi** [comment]
@MountainDrew Feel free to feedback

>  It's just a method to overwrite the implemented function, effectively stubbing it. It checks a number of things like called with/number of times

Depends on what tool you use for testing, it is better to check it in the documentation for testing tool.
