### ISSUE TITLE
No provider for "framework:webpack"

### ISSUE THREAD

**Issue by stevenvachon** [webpack-contrib/karma-webpack#389]
This is related to #380. @daKmoR

* Operating System: macOS 10.14.2
* Node Version: 10.15.0
* NPM Version: 6.4.1
* webpack Version: 4.28.4
* karma-webpack Version: 5.0.0 (branch)

### Expected Behavior
It should use the "webpack" framework.

### Actual Behavior
```
21 01 2019 12:51:33.487:ERROR [karma-server]: Server start failed on port 9876: Error: No provider for "framework:webpack"! (Resolving: framework:webpack)
```

### Code
https://github.com/stevenvachon/karma-webpack-issue

### How Do We Reproduce?
```shell
npm test
```

**Comment by matthieu-foucault** [comment]
Use the `next` branch instead. Sorry, that `5.0.0` branch should have been deleted

**Comment by matthieu-foucault** [comment]
Using the version published under the `@dev` tag would be recommended though if you want to use the alpha version (`npm i -D karma-webpack@dev`)

**Comment by stevenvachon** [comment]
Okay, thank you. My repository appears to run properly now.
