### ISSUE TITLE
Add 'karma-preprocessor' to keywords

### ISSUE THREAD

**Issue by rensbaardman** [webpack-contrib/karma-webpack#397]
Documentation Is:

- [x] Missing
- [ ] Needed
- [ ] Confusing
- [x] Not Sure?

### Please Explain in Detail...
Not sure if 'documentation' is the right type for this issue, but most/all karma preprocessors have the `npm`-tag `karma-preprocessor` to make them easily discoverable. E.g. a default `karma init` run generates a config file that points to https://www.npmjs.com/search?q=keywords:karma-preprocessor to look for more preprocessors. [Searching for 'webpack' there](https://www.npmjs.com/search?q=keywords%3Akarma-preprocessor%20webpack) doesn't give this package, which it should.

### Your Proposal for Changes
I'm an `npm`-noobie, but it looks like expanding the `keywords`-list in `package.json` would suffice. But then: why is the keyword `webpack` not already showing up on [the npm-page for `karma-webpack`](https://www.npmjs.com/package/karma-webpack)?

edit: I see now, that the version on npmjs.com is already 5 months old, probably predating the [inclusion of the `webpack`-keyword.](https://github.com/webpack-contrib/karma-webpack/commit/2a4d3bbaa4d0daf13e4dbb6af45bd0703407d7db#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R86)

edit2: considering the other preprocessors, maybe `karma` and `karma-plugin` would be appropriate keywords too.

**Comment by ryanclark** [comment]
Done and released in v4.0.0 - thank you!
