### ISSUE TITLE
Publish @next under @latest

### ISSUE THREAD

**Issue by ryanclark** [webpack-contrib/karma-webpack#408]
To avoid confusion like in #406, let's publish `@next` under `@latest`.

### Expected Behavior

`npm install webpack karma-webpack` installs a version of `karma-webpack` incompatible with the version of `webpack` installed 

### Actual Behavior

`npm install webpack karma-webpack` should install a version of `karma-webpack` that's compatible with `webpack`

**Comment by evilebottnawi** [comment]
Done https://www.npmjs.com/package/karma-webpack
