### ISSUE TITLE
4.0.0 - Cannot find plugin "karma-webpack"

### ISSUE THREAD

**Issue by limonte** [webpack-contrib/karma-webpack#415]
I just bumped karma-webpack to ^4.0.0 https://github.com/sweetalert2/sweetalert2/commit/12931d1bd4e0656c47112f46557df60c1f0de4ef and now something is broken:
https://travis-ci.org/sweetalert2/sweetalert2/builds/542866172

Am I missing something or `4.0.0` is broken?

**Comment by junkurihara** [comment]
Same problem. Even a single line `require('karma-webpack')` doesn't work for the 4.0.0 package installed through npm in karma.conf.js, `karma-webpack:4.0.0-rc-6` works fine though.

**Comment by evilebottnawi** [comment]
WIP on this

**Comment by ryanclark** [comment]
Fixed in v4.0.1
