### ISSUE TITLE
Transpiled files missing from published NPM package (v4.0.0)

### ISSUE THREAD

**Issue by caseyWebb** [webpack-contrib/karma-webpack#416]
- Operating System: Arch Linux (Kernel 5.1.4)
- Node Version: 12.3.1
- NPM Version: 6.9.0 (But I use yarn, version 1.16.0)
- webpack Version: 4.33.0
- karma-webpack Version: 4.0.0

### Expected Behavior

package.json -> main should point to a file that exists

### Actual Behavior

`./lib` is non-existent :cry: 

I assume babel was not ran before publishing

### How Do We Reproduce?

```
yarn add karma-webpack
```

check `node_modules/karma-webpack`

**Comment by caseyWebb** [comment]
#415 is probably the same issue

**Comment by ryanclark** [comment]
Closing as a duplicate, fixed in #417

**Comment by ryanclark** [comment]
Fixed in v4.0.1
