### ISSUE TITLE
Security vulnerability in lodash version used by karma-webpack

### ISSUE THREAD

**Issue by michdsouza** [webpack-contrib/karma-webpack#425]
- Operating System: Mac OS 10.14.5
- Node Version: 11.12.0
- NPM Version: 6.7.0
- webpack Version: 4.0.4
- karma-webpack Version: 3.0.0

### Expected Behavior

Upgrade to lodash version >=4.17.12

### Actual Behavior

| high          | Prototype Pollution                                                       |   
|---------------|---------------------------------------------------------------------------|
| Package       | lodash                                                                    |
| Patched in    | >=4.17.12                                                                 |
| Dependency of | karma-webpack                                                             |
| Path          | karma-webpack > lodash                                                    |
| More info     | https://www.npmjs.com/advisories/1065                                     |

### Code

N/A

### How Do We Reproduce?

Running a `yarn audit`

**Comment by evilebottnawi** [comment]
Update webpack and webpack-karma to latest version
