### ISSUE TITLE
Using file-based sourcemap instead of inline

### ISSUE THREAD

**Issue by dtabuenc** [webpack-contrib/karma-webpack#51]
For some reason inline sourcemaps make tests start up and run incredibly slow in current versions of Chrome and PhantomJS2.  It would be nice to be able to use external sourcemaps (which run much quicker). The easiest way I can think to do this is to simply change the URL on the bottom of the bundle to reference "_karma_webpack_/path/to/bundle.js.map". Is there any way to configure this? Alternatively, it might be interesting to register a customFileHandler for each [entry].js.map that then pulls the map from the middleware.

**Comment by dtabuenc** [comment]
I've currently managed to get this working using the SourceMapDevToolPlugin


```js
 new webpack.SourceMapDevToolPlugin({
                    columns: false,
                    filename: '[file].map[query]',
                    lineToLine: false,
                    module: false,
                    append: '\n//# sourceMappingURL=/_karma_webpack_/[url]'
                })
```

This only works in the case I'm using a single entry point (or all the entry points are in the same folder), since the absolute path to the source map folder is hard coded in the "append" line.

**Comment by tur-nr** [comment]
How did you get the source maps to be created in the first place.

```coffeescript
webpack = require 'webpack'

module.exports =
    module:
        loaders: [
            { test: /\.coffee$/, loader: 'coffee' }
        ]
    resolve:
        root: [
            "#{__dirname}/"
            "#{__dirname}/bower_components"
        ]
        extensions: [
            ''
            '.js'
            '.coffee'
        ]
    plugins: [
        new webpack.ResolverPlugin(
            new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin 'bower.json', ['main']
        )
    ]
    debug: true
    devtool: 'inline-source-map'
```

I have a single entry point and if run webpack with the following:

```shell
webpack input.coffee output.js
```

I can see that `output.js` has inline sourcemaps, base64 at the end of the file. *However*, if I run the same configuration through the plugin, I don't get any inline source maps? It's like the plugin just disregards my `devtool` property?

**Comment by dtabuenc** [comment]
The devtool property is just a shorthand for configuring the plugin for you. If you use the plugin yourself you are basically doing a custom configuration INSTEAD of letting devtool configure it for you. If you need to enable inline sourcemaps you would have to look at the options the plugin itself takes.

**Comment by aaronjensen** [comment]
@dtabuenc Hey Dan :stuck_out_tongue_winking_eye:  Does this work for you still? `/_karma_webpack_/` doesn't seem to be exposed over karma, so it's not finding it afaict. Are you using that plugin w/ karma-webpack? Hope all is well over there for ya :)
