### ISSUE TITLE
Using an absolute spec path outside of karma basePath

### ISSUE THREAD

**Issue by maxkostow** [webpack-contrib/karma-webpack#82]
I'm trying to write a script that dynamically builds the webpack entry file to get the best of both worlds (Usage/Alternate Usage in the readme.) from command line arguments. I'm putting this file in a temporary directory so the entry in the files array is an absolute path. However it looks like the require paths are somehow tied to the karma `basePath`. Is what I'm trying to do a terrible idea? Am I missing a crucial detail? Do I need to slightly tweak the karma-webpack implementation?

**Comment by d3viant0ne** [comment]
@maxkostow - Need to know if this is still an issue. For the sake of efficiency, we are starting with current versions and the team can work back from there.

If this is still an issue on a recent version of the loader & it's peerDeps, please respond here so we can get this properly triaged.

**Comment by maxkostow** [comment]
Yeah this is still an issue.

**Comment by d3viant0ne** [comment]
Thanks, well get it on the list and get into it.
